# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Remindify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Remindify
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'DateTimePicker'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwipeCellKit'
  pod 'MBProgressHUD'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
end
